Station health bar in station details screen
WeatherXM/wxm-ios pull request #166
Opened 2024-10-17 09:20 UTC by pantelisss

## **Why?**
Health metrics in station details screen
### **How?**
- Refactor observations -> overview
- Added health metrics section
- Removed error/warning indication (border) from station card
### **Testing**
Make sure everything looks as expected 
### **Additional context**
fixes fe-1196

2024-10-17 09:49 UTC, PavlosTze requested changes
Except my comments from #164 which stand here as well I have some more minor issues:
1. I think the margin at the top is smaller for "Station Health"
2. In the bottom sheet some text is missing for the "Location Quality".
3. For iPhone 15 Pro the text is cropped in the Data Quality chip when it's 100%, I think we should use smaller horizontal padding there in the chips?

2024-10-17 14:30 UTC, PavlosTze reviewed
All good, let's wait for the "NO_LOCATION" case to be resolved so we can move forward with this.

2024-10-21 11:09 UTC, pantelisss commented
@PavlosTze the updates in station details are done, you can review again

2024-10-21 12:10 UTC, PavlosTze approved these changes

2024-10-25 07:56 UTC, closed without merging