Feature/fe 625 UI card components states
WeatherXM/wxm-ios pull request #25
Opened 2024-02-21 13:24 UTC by pantelisss

## **Why?**
Redesign of rewards tab and timeline
### **How?**
- Created new UI elements
  - `TotalRewardsView`: The top card
  - `DailyRewardCardView`: The main card
  - `WeeklyStreakView`: The weekly timeline
  - `NoRewardsView`: For empty state
  - `AnnouncementCardView`: Shows the mainnet banner
- Major refactor and cleanup 
### **Testing**
Run the mock scheme
### **Additional context**
Reward details screen seems broken, will be implemented later
fixes fe-625

2024-02-22 10:12 UTC, PavlosTze requested changes
Some UI changes first Panteli.

Station Name: `Exotic Pecan Aurora`
1. There is an info annotation on the rewards tab and on the rewards timeline, I can see it on Android + API response but it's missing here.
2. On Rewards Timeline please remove the "View Reward Details" button, it will only be shown on an annotation otherwise the whole card is clickable per the design.
3. The "timeline line" seems bigger than the design and the date point doesn't seem to be at the center of it, screenshot:
<img width="197" alt="image" src="https://github.com/WeatherXM/wxm-ios/assets/19330987/d0869621-89d2-4954-8f4c-053c709d48a9">

4. Please confirm that the boosts icon color is the correct one, seems way darker than Android, but maybe it's the Mac screen.
5. The "Weekly Streak" card needs elevation.


--------
Station Name: `High Denim Ice`
1. I had 0 reward score for every day of the weekly streak, we need a small red circle at the bottom in those cases. Right now only grey-ish bars are shown, these should be shown only when `base_reward_score` is null, for every other case we should use an **offset to start the bars height**. In the designs, the first bar which has the red circle at the bottom is equilevant to 0 reward score.

2024-02-22 15:51 UTC, pantelisss commented
@PavlosTze Great catches

2024-02-23 09:05 UTC, PavlosTze commented on PresentationLayer/Extensions/Domain Extensions/NetworkDeviceRewardsSummaryResponse+.swift
> +	}
If this is for showing the empty screen, I think based on Peris spec, we should show the empty screen when `total_rewards == 0`, so this `var isEmpty` here is not entirely correct.

2024-02-23 09:09 UTC, PavlosTze commented on PresentationLayer/UI Components/Screens/Daily Rewards /RewardDetailsViewModel.swift
>  	}
Let's remove it entirely now? I'm not sure we need it anymore.

2024-02-23 16:20 UTC, PavlosTze commented on PresentationLayer/Extensions/Domain Extensions/NetworkDeviceRewardsSummaryResponse+.swift
> +	}
Yes, that's why I suggest showing the empty screen when total rewards are zero, and not when checking the latest & timeline if they are equivalent of nil.

Because we agreed to the first option based on the spec document, and I'm not sure what the API will send on the first run in regards to latest & timeline.

2024-02-23 16:31 UTC, pantelisss commented on PresentationLayer/UI Components/Screens/Daily Rewards /RewardDetailsViewModel.swift
>  	}
Removed, however the whole screen will be changed

2024-02-23 16:32 UTC, pantelisss commented on PresentationLayer/Extensions/Domain Extensions/NetworkDeviceRewardsSummaryResponse+.swift
> +	}
Ok no prob, gonna change the condition

2024-02-26 08:31 UTC, PavlosTze approved these changes

2024-02-27 15:42 UTC, merged