Data models
WeatherXM/wxm-ios pull request #28
Opened 2024-03-01 16:20 UTC by pantelisss

## **Why?**
Data models for reward details
### **How?**
Declared all necessary models and endpoints for reward details screen
### **Testing**
Make sure the models are declared properly 
### **Additional context**
fixes fe-654

2024-03-01 23:57 UTC, PavlosTze requested changes

2024-03-01 23:57 UTC, PavlosTze commented on wxm-ios/DomainLayer/DomainLayer/Entities/Codables/Me/Network/NetworkDeviceRewardDetailsResponse.swift
> +	}
I think that's wrong, as we have an AnnotationSummary there which has a different format?

e.g.
```
"annotation_summary": [
    {
      "severity_level": "INFO",
      "group": "NO_WALLET",
      "title": "Minor Sensor Issues",
      "message": "Station is doing great! Minor issues detected during our data quality checks, that may be related to occasional sensor inaccuracies. That can happen once in a while.",
      "doc_url": "https://docs.weatherxm.com/project/rewards-troubleshooting#sensor-problems"
    }
  ]
```

2024-03-04 09:08 UTC, pantelisss commented on wxm-ios/DomainLayer/DomainLayer/Entities/Codables/Me/Network/NetworkDeviceRewardDetailsResponse.swift
> +	}
Not sure I understand. Do you mean that is better to rename the mode from `RewardAnnotation` to `AnnotationSummary`?

2024-03-04 10:44 UTC, PavlosTze commented on wxm-ios/DomainLayer/DomainLayer/Entities/Codables/Me/Network/NetworkDeviceRewardDetailsResponse.swift
> +	}
Hmm no you are right, my bad. Regarding the above though, the `score` isn't defined in the API response, right?

2024-03-04 11:23 UTC, pantelisss commented on wxm-ios/DomainLayer/DomainLayer/Entities/Codables/Me/Network/NetworkDeviceRewardDetailsResponse.swift
> +	}
😩 score is removed now... 
There was in the initial mock response

2024-03-04 11:37 UTC, PavlosTze approved these changes

2024-03-04 14:15 UTC, merged