Boos Details UI components implementation
WeatherXM/wxm-ios pull request #34
Opened 2024-03-11 10:21 UTC by pantelisss

## **Why?**
Boost details screen
### **How?**
- Handle unknown boosts in the reward details screen
- Boost details screen implementation
- Integrated `nuke` library for async image load with caching
### **Testing**
Make sure boosts are presented properly using the dev server
### **Additional context**
fixes fe-663

2024-03-11 13:54 UTC, PavlosTze approved these changes
Good job @pantelisss . Everything looks OK. Found only one minor issue, probably an API issue as the response is random, but had to report it:

<img width="327" alt="image" src="https://github.com/WeatherXM/wxm-ios/assets/19330987/75ffd41d-8d64-47bf-92ab-aea3a009a638">

2024-03-12 21:29 UTC, PavlosTze requested changes
Sorry @pantelisss , caught some issues in the other PR but I think this is one is more relevant to report them.

2024-03-12 21:29 UTC, PavlosTze commented on PresentationLayer/Extensions/Domain Extensions/NetworkDeviceRewardDetailsResponse+.swift
> +			  score: rewardScore ?? 0,
Hmm this looks wrong, as we want the `score` to be nullable in order to remove the texts on boost details screen if reward score is missing. And if I get it correctly that's not possible with this line here as it defaults to 0.

2024-03-12 21:29 UTC, PavlosTze commented on PresentationLayer/UI Components/Screens/Daily Rewards /Components/BoostsView.swift
> +				}
I removed the `img_url` from the mock json and it crashed here. We need to have a fallback if `img_url` is missing, to add a custom hardcoded background, I've used `dark_bg` color for that.

2024-03-13 10:55 UTC, pantelisss commented
Great catches @PavlosTze

2024-03-13 11:04 UTC, PavlosTze approved these changes

2024-03-13 12:48 UTC, merged