List of alerts screen
WeatherXM/wxm-ios pull request #54
Opened 2024-04-02 13:54 UTC by pantelisss

## **Why?**
Show the low battery warning in the station's alert list
### **How?**
UI fixes and handling of low battery warning
### **Testing**
Just like the base branch PR use mock scheme and `get_user_devices.json` and make sure everything everything looks good
### **Additional context**
fixes fe-743

2024-04-03 08:15 UTC, PavlosTze requested changes
Good job @pantelisss , just the header needs some adjustments as it's different than the design.

2024-04-03 13:16 UTC, pantelisss commented
@PavlosTze ready

2024-04-03 14:11 UTC, PavlosTze reviewed
@pantelisss The subtitle (the station name below "Alerts"), feels too big, is it 12dp per the designs?

2024-04-09 09:57 UTC, PavlosTze approved these changes

2024-04-10 08:36 UTC, merged