Claim wizard step 1
WeatherXM/wxm-ios pull request #76
Opened 2024-05-15 13:06 UTC by pantelisss

## **Why?**
The first step of claim wizard for D1 and M5
### **How?**
- `ClaimDeviceBeginViewModel` for D1 flow
- `ClaimDeviceM5BeginViewModel` subclass of `ClaimDeviceBeginViewModel` for m5 flow
### **Testing**
Make sure the 2 screens are rendered as expected
### **Additional context**
fixes fe-829

2024-05-15 17:59 UTC, PavlosTze requested changes
Everything looks good but there are 2 minor UI issues except my other comments below:
1. The title of the screen should be `Claim M5 | WiFi` and `Claim D1 | WiFi` per the designs.
2. The text color in the **light theme** seems black, whereas in designs is `darkGrey`.

2024-05-15 17:59 UTC, PavlosTze commented on PresentationLayer/Constants/Strings/DisplayedLinks.swift
> +				return "https://www.youtube.com/watch?v=sUJEwuFq1CE"
It doesn't have a video I think?

2024-05-16 07:05 UTC, pantelisss commented on PresentationLayer/Constants/Strings/DisplayedLinks.swift
> +				return "https://www.youtube.com/watch?v=sUJEwuFq1CE"
Correct, I forgot to remove it from the constants

2024-05-16 08:26 UTC, PavlosTze approved these changes

2024-05-16 08:49 UTC, merged