Claim wizard step 4 confirm station location
WeatherXM/wxm-ios pull request #79
Opened 2024-05-20 08:59 UTC by pantelisss

## **Why?**
The last step of claiming flow and submission
### **How?**
- Made a reusable component for location selection from map (`SelectLocationMapView`). This component will also be used in "edit location" from device info. 
- `ClaimDeviceLocationView` is the view for the last step
- Implemented also the claim request functionality
### **Testing**
Test the flow end to end.
Make sure everything works as before in the edit location screen from the device info
### **Additional context**
fixes fe-832
Cleanup and the updates for the helium flow will be performed in the upcoming PR

2024-05-20 11:02 UTC, PavlosTze requested changes
Some changes needed Panteli:
1. The top bar has rounded edges (which are visible in dark theme actually where the background is different than the rest of the screen)
2. In the result screen the animation + title + subtitle should be centered in the screen and not at the top

I also didn't succeed claiming a D1 device, I used the testing script but I always got "Invalid serial number" error.

2024-05-21 07:27 UTC, pantelisss commented
Good catches @PavlosTze ! Now is ready

2024-05-21 09:08 UTC, pantelisss commented
@PavlosTze I've made the fixes as we discussed

2024-05-21 09:13 UTC, PavlosTze approved these changes

2024-05-21 09:15 UTC, merged